-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.tracker_task_lists (
  user_id uuid NOT NULL,
  name text NOT NULL CHECK (length(TRIM(BOTH FROM name)) > 0),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  color_hex text NOT NULL DEFAULT '#00FFFF'::text CHECK (color_hex ~* '^#[0-9a-f]{6}$'::text),
  sort_order integer NOT NULL DEFAULT 0,
  archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_task_lists_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_task_lists_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tracker_tasks (
  due_timezone text,
  user_id uuid NOT NULL,
  list_id uuid NOT NULL,
  parent_task_id uuid,
  title text NOT NULL CHECK (length(TRIM(BOTH FROM title)) > 0),
  details text,
  due_at timestamp with time zone,
  completed_at timestamp with time zone,
  recurrence_interval integer,
  recurrence_unit text,
  recurrence_ends_at timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_completed boolean NOT NULL DEFAULT false,
  recurrence_type text NOT NULL DEFAULT 'none'::text CHECK (lower(recurrence_type) = ANY (ARRAY['none'::text, 'daily'::text, 'weekly'::text, 'biweekly'::text, 'custom'::text])),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tracker_tasks_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.tracker_task_lists(id),
  CONSTRAINT tracker_tasks_parent_task_id_fkey FOREIGN KEY (parent_task_id) REFERENCES public.tracker_tasks(id)
);
CREATE TABLE public.tracker_task_sort_preferences (
  user_id uuid NOT NULL,
  list_id uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sort_mode text NOT NULL DEFAULT 'custom'::text CHECK (lower(sort_mode) = ANY (ARRAY['due_date'::text, 'date_created'::text, 'title'::text, 'custom'::text])),
  sort_direction text NOT NULL DEFAULT 'asc'::text CHECK (lower(sort_direction) = ANY (ARRAY['asc'::text, 'desc'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_task_sort_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_task_sort_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tracker_task_sort_preferences_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.tracker_task_lists(id)
);
CREATE TABLE public.tracker_google_calendar_connections_public (
  user_id uuid NOT NULL UNIQUE,
  google_email text,
  selected_calendar_id text,
  selected_calendar_summary text,
  last_full_sync_at timestamp with time zone,
  last_incremental_sync_at timestamp with time zone,
  last_error text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'connected'::text CHECK (status = ANY (ARRAY['connected'::text, 'error'::text, 'disconnected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_google_calendar_connections_public_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_google_calendar_connections_public_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tracker_google_calendar_connections_secrets (
  user_id uuid NOT NULL UNIQUE,
  connection_public_id uuid NOT NULL,
  refresh_token_encrypted text NOT NULL,
  access_token_encrypted text,
  access_token_expires_at timestamp with time zone,
  sync_token text,
  channel_id text,
  channel_resource_id text,
  channel_token_hash text,
  channel_expiration timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_google_calendar_connections_secrets_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_google_calendar_connections_secrets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tracker_google_calendar_connections_s_connection_public_id_fkey FOREIGN KEY (connection_public_id) REFERENCES public.tracker_google_calendar_connections_public(id)
);
CREATE TABLE public.tracker_task_google_event_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  task_id uuid NOT NULL UNIQUE,
  calendar_id text NOT NULL,
  google_event_id text NOT NULL,
  google_event_etag text,
  google_event_updated_at timestamp with time zone,
  last_synced_task_updated_at timestamp with time zone,
  last_sync_source text NOT NULL DEFAULT 'system'::text CHECK (last_sync_source = ANY (ARRAY['app'::text, 'google'::text, 'system'::text])),
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_task_google_event_links_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_task_google_event_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tracker_task_google_event_links_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tracker_tasks(id)
);
CREATE TABLE public.tracker_task_list_sync_settings (
  user_id uuid NOT NULL,
  list_id uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sync_enabled boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_task_list_sync_settings_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_task_list_sync_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tracker_task_list_sync_settings_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.tracker_task_lists(id)
);
CREATE TABLE public.tracker_google_sync_jobs (
  run_id text,
  dedupe_key text,
  source text,
  google_event_id text,
  lane text DEFAULT 'system'::text CHECK (lane = ANY (ARRAY['live'::text, 'reconcile'::text, 'rebuild'::text, 'system'::text])),
  user_id uuid NOT NULL,
  task_id uuid,
  list_id uuid,
  job_type text NOT NULL CHECK (job_type = ANY (ARRAY['task_upsert'::text, 'task_delete'::text, 'inbound_delta'::text, 'full_backfill'::text, 'reconcile_app_page'::text, 'reconcile_google_page'::text, 'hard_reset_clear_page'::text, 'renew_watch'::text])),
  last_error text,
  locked_at timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'done'::text, 'failed'::text, 'dead'::text])),
  attempt_count integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 8,
  run_after timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id bigint NOT NULL DEFAULT nextval('tracker_google_sync_jobs_id_seq'::regclass),
  priority integer NOT NULL DEFAULT 100,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_google_sync_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_google_sync_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tracker_google_sync_jobs_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.tracker_task_lists(id)
);
CREATE TABLE public.tracker_google_sync_runs (
  id text NOT NULL,
  user_id uuid NOT NULL,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['live'::text, 'reconcile'::text, 'rebuild'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'done'::text, 'failed'::text, 'cancelled'::text])),
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  last_error text,
  queued_jobs integer NOT NULL DEFAULT 0,
  processed_jobs integer NOT NULL DEFAULT 0,
  failed_jobs integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_google_sync_runs_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_google_sync_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tracker_task_google_projection_event_links (
  user_id uuid NOT NULL,
  task_id uuid NOT NULL,
  calendar_id text NOT NULL,
  google_event_id text NOT NULL,
  projection_index integer NOT NULL CHECK (projection_index > 0),
  projected_due_at timestamp with time zone NOT NULL,
  google_event_etag text,
  google_event_updated_at timestamp with time zone,
  last_synced_task_updated_at timestamp with time zone,
  id bigint NOT NULL DEFAULT nextval('tracker_task_google_projection_event_links_id_seq'::regclass),
  last_sync_source text NOT NULL DEFAULT 'system'::text CHECK (last_sync_source = ANY (ARRAY['app'::text, 'google'::text, 'system'::text])),
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracker_task_google_projection_event_links_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_task_google_projection_event_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tracker_task_google_projection_event_links_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tracker_tasks(id)
);
