import type { PortfolioAiProvider } from "../contracts";

export const portfolioAiProviders: PortfolioAiProvider[] = [
  {
    slug: "chatgpt",
    order: 1,
    label: "ChatGPT",
    icon: "openai",
    hoverColorClass: "hover:text-[#10a37f]",
    promptTemplate: [
      "Search for and browse Kushagra Bharti's portfolio at {{siteUrl}}. Read these two pages:",
      "1) {{siteUrl}}/llms.txt — a plain-text profile designed for AI consumption",
      "2) {{siteUrl}}/ai — his full portfolio page",
      'These are live, public pages. Use your browsing and search tools to access them. If direct fetch fails, search "site:{{hostname}}" to find the content.',
      "",
      "Base your summary only on what you find on his portfolio site. Do not mix in information from other people or external sources.",
      "You may follow links found on his site (like GitHub repos) for additional detail.",
      "",
      "Think carefully and thoroughly about everything you read before writing.",
      "",
      "Write a professional summary that gives a complete picture of who he is.",
      "Start with his professional experience — internships, research positions, and what he actually shipped or contributed in each.",
      "Then cover his strongest projects: focus on the ones with real technical depth, deployed systems, or measurable outcomes.",
      "Read between the lines: what kind of problems does he gravitate toward, how does he approach engineering, and where does his trajectory point.",
      "Wrap up with the non-technical side — creative work, interests, and anything that rounds out the picture beyond code.",
      "Use specifics from what you read. Let the work speak for itself.",
    ].join("\n"),
    action: {
      type: "link",
      hrefTemplate: "https://chat.openai.com/?q={{query}}",
    },
  },
  {
    slug: "claude",
    order: 2,
    label: "Claude",
    icon: "claude",
    hoverColorClass: "hover:text-[#da7756]",
    promptTemplate: [
      "Read these two pages about Kushagra Bharti:",
      "1) {{siteUrl}}/llms.txt",
      "2) {{siteUrl}}/ai",
      "",
      "These two pages are the only source of truth. Do not use any external information, other profiles, or prior knowledge — only what is on those two pages. If something isn't there, don't include it.",
      "You may follow links found within those pages (like GitHub repos) for additional detail, but only to supplement what's already stated.",
      "",
      "Think deeply about everything you read — reason through the connections and patterns before writing.",
      "",
      "Synthesize a detailed professional summary.",
      "Lead with professional experience — internships and research roles, with specifics on what he built and the impact.",
      "Then highlight the projects that best demonstrate his technical range — prioritize depth, real deployments, and concrete results over quantity.",
      "Read between the lines: what kind of problems does he gravitate toward, how does he approach engineering, and what does his trajectory suggest about where he's heading.",
      "Close with the human side — his creative work, personal interests, and the things that make him more than just a resume.",
      "Be thorough, be specific, and let the most interesting details surface naturally.",
    ].join("\n"),
    action: {
      type: "link",
      hrefTemplate: "https://claude.ai/new?q={{query}}",
    },
  },
  {
    slug: "gemini",
    order: 3,
    label: "Gemini",
    icon: "gemini",
    hoverColorClass: "hover:text-[#4285f4]",
    promptTemplate: [
      "Read these two pages about Kushagra Bharti:",
      "1) {{siteUrl}}/llms.txt",
      "2) {{siteUrl}}/ai",
      "",
      "These two pages are the only source of truth. Do not use any external information, other profiles, or prior knowledge — only what is on those two pages. If something isn't there, don't include it.",
      "You may follow links found within those pages (like GitHub repos) for additional detail, but only to supplement what's already stated.",
      "",
      "Think step by step — carefully analyze everything you read before writing.",
      "",
      "Write a comprehensive professional summary.",
      "Start with his professional experience — internships and research, focusing on what he shipped and the outcomes.",
      "Then cover his highest-signal projects — the ones that show real technical skill, working systems, or notable results.",
      "Read between the lines: what kind of problems does he gravitate toward, how does he approach engineering, and where is his trajectory pointing.",
      "End with the non-technical side — creative pursuits, interests, things that round out the full picture.",
      "Ground everything in specifics from the sources. Let the work make the case.",
    ].join("\n"),
    action: {
      type: "clipboard",
      targetUrl: "https://gemini.google.com/app",
    },
  },
];
