import type { PortfolioExperience } from "../contracts";

export const portfolioExperiences: PortfolioExperience[] = [
  {
    slug: "utsw-tsai-lab-machine-learning-engineering-intern",
    order: 1,
    dateRange: "Feb 2026 - Present",
    category: "Research",
    timelineTone: "active",
    position: "Machine Learning Engineer Intern at UT Southwestern Medical Center, Tsai Lab",
    summary:
      "Building computer vision tooling for behavioral neuroscience: a DeepLabCut/SuperAnimal pipeline that turns 3-chamber mouse videos into pose tracks, behavioral metrics, QC outputs, and CSV/XLSX scorecards for lab review.",
    description: [
      "Built a DeepLabCut/SuperAnimal video-analysis pipeline for 3-chamber social-interaction videos, converting raw mouse videos into pose tracks, behavioral metrics, QC artifacts, and scorecards used for lab review.",
      "Automated the core workflow from crop → enhancement → pose inference → behavior scoring → QC → CSV/XLSX export, making the analysis more reproducible and less dependent on manual script-by-script execution.",
      "Improved pose tracking stability by 56.9% across 15 clip pairs using likelihood-aware filtering and interpolation, reducing frame-to-frame coordinate jitter in usable benchmark clips.",
      "Corrected behavior-scoring logic around discrimination index (DI), ambiguous cup contact, interpolation boundaries, and chamber occupancy so downstream behavioral metrics better match the intended experimental definitions.",
      "Built QC tooling to surface unreliable trials instead of hiding them, including occlusion/body-length flags and pose summaries that make failed or low-confidence tracking easier to diagnose.",
      "Exported final analysis into lab-friendly CSV/XLSX scorecards, turning long-form behavior summaries into a format that is easier for researchers to inspect, compare, and hand off.",
      "Prepared targeted DeepLabCut fine-tuning infrastructure (sampled frames, pseudo-labels, contact sheets, and project scaffolding) while keeping measured filtering gains separate from unverified model fine-tuning gains."
    ],
    tags: [
      "Machine Learning",
      "Computer Vision",
      "DeepLabCut",
      "SuperAnimal",
      "Markerless Pose Estimation",
      "Behavioral Analysis",
      "Behavioral Phenotyping",
      "Neuroscience",
      "Autism Research",
      "Pose Tracking",
      "Video Analysis",
      "Python",
      "OpenCV",
      "pandas",
      "NumPy",
      "HDF5",
      "CSV/XLSX",
      "QC Tooling",
      "Research Software"
    ],
    companyLink: "https://labs.utsouthwestern.edu/tsai-lab"
  },
  {
    slug: "glydr-technical-lead-consultant",
    order: 2,
    dateRange: "Jan 2026 - Present",
    category: "Product / Consulting",
    timelineTone: "active",
    position: "Software Engineer at Glydr.gg",
    summary:
      "Leading technical/product direction for Glydr.gg’s customer-facing configuration hub: a Railway-deployed React/Vite + Fastify platform for discovering, importing, and managing foot-controller configs.",
    description: [
      "Led technical/product direction for a 5-person team building Glydr.gg’s configuration hub, translating client needs into public config discovery, Steam login, admin tools, and Control Panel import flows.",
      "Architected a React/Vite + Fastify platform backed by Postgres/Drizzle, with Railway deployment across frontend, backend API, worker, and database services.",
      "Built a config system around checksum-versioned Control Panel JSON payloads, enabling stable deduplication, repeat-upload handling, and exact-version imports.",
      "Engineered secure import handoffs using hashed 10-minute tokens, fetch caps, and rate limits so users can move selected configs into Glydr’s Control Panel without exposing large/private config payloads in URLs.",
      "Implemented Steam OpenID-based identity and backend-owned sessions with HTTP-only cookies, CSRF checks, admin allowlists, and protected product actions.",
      "Modeled the product domain with a relational schema covering users, Steam identities, sessions, games, categories, configs, immutable versions, imports, handoff tokens, jobs, and audit logs.",
      "Built product flows for public game/category browsing, config detail pages, private config uploads, admin-published official configs, Steam library context, and import success states.",
      "Verified launch readiness with passing typecheck/build and backend tests covering Control Panel JSON parsing, stable checksums, and invalid-payload rejection."
    ],
    tags: [
      "Technical Leadership",
      "Product Engineering",
      "Client-Facing Development",
      "Full-Stack Development",
      "TypeScript",
      "React",
      "Vite",
      "Fastify",
      "PostgreSQL",
      "Drizzle ORM",
      "Steam OpenID",
      "Railway",
      "API Design",
      "Authentication",
      "CSRF",
      "Rate Limiting",
      "Config Versioning",
      "Checksum Validation",
      "Admin Tooling",
      "Consulting"
    ],
    companyLink: "https://glydr.gg/"
  },
  {
    slug: "ut-dallas-undergraduate-researcher-monopolybench",
    order: 3,
    dateRange: "Apr 2025 - Present",
    category: "Research",
    timelineTone: "active",
    position: "Undergraduate Researcher at UT Dallas (LLM Evaluation)",
    summary:
      "Built MonopolyBench, a deterministic multi-agent LLM harness where tool-calling agents play full Monopoly games, enabling research on long-horizon planning, negotiation, deception, and bias.",
    description: [
      "Built MonopolyBench as a deterministic multi-agent LLM evaluation harness where tool-calling agents play full Monopoly games under an authoritative rules engine.",
      "Designed each turn around state/history memory, schema-bound actions, and tool-call traces so model behavior is constrained, inspectable, and reproducible.",
      "Implemented a deterministic engine + arena + telemetry stack: seeded randomness, legal action menus, strict validation, corrective retry, deterministic fallback, and full run artifact logging.",
      "Logged complete traces for decisions, prompts, raw model responses, parsed actions, applied actions, events, snapshots, and summaries, making runs debuggable instead of black-box.",
      "Built the system to support live spectator viewing and headless batch evaluation, with FastAPI/WebSocket streaming and a render-only React UI.",
      "Designed the benchmark for an upcoming LLM agent paper studying planning, negotiation, deception, and bias in long-running, multi-agent game environments.",
      "Research directions include win-rate ranking across models, TrueSkill ratings, micro-decision suites, negotiation/bluffing analysis, and bias experiments through controlled player descriptors."
    ],
    tags: [
      "LLM Evaluation",
      "AI Agents",
      "Multi-Agent Systems",
      "Tool Calling",
      "Function Calling",
      "Agent Benchmarking",
      "Deterministic Simulation",
      "Game AI",
      "Long-Horizon Planning",
      "Negotiation",
      "Deception",
      "Bias Evaluation",
      "Telemetry",
      "Event Sourcing",
      "Replayable Artifacts",
      "Python",
      "FastAPI",
      "WebSockets",
      "React",
      "TypeScript",
      "Vite",
      "Zod",
      "JSON Schema",
      "Pytest"
    ],
    companyLink: "https://github.com/KushagraBharti/MonopolyBench"
  },
  {
    slug: "ut-dallas-undergraduate-researcher-optimization",
    order: 4,
    dateRange: "Apr 2025 - Present",
    category: "Research",
    timelineTone: "active",
    position: "Independent Researcher (Optimization + ML) at UT Dallas",
    summary:
      "Built paper-faithful optimization solvers and a solver-labeled dataset pipeline for 1D drone coverage planning, with benchmarks and QC gates to support supervised, GNN, and RL experiments on optimal tour planning.",
    description: [
      "Implemented 4 paper-faithful solvers for 1D drone coverage planning (greedy + DP), including exact plan reconstruction so solver outputs can become usable training labels.",
      "Built an end-to-end data pipeline from instance generation → gold labels → featurization hooks → QC, enabling ML training on optimal solutions instead of heuristic approximations.",
      "Measured labeling throughput on a verified run: 370 labeled instances in 2.71s (~136 samples/s), writing ~280KB of JSONL data with automated validation of feasibility and coverage constraints.",
      "Configured defaults for a 67,000-sample labeled dataset across train/test/shifted/extrap/stress splits, supporting generalization and distribution-shift evaluation.",
      "Benchmarked exact solver scaling: dp_full stays under 1s up to n=1024 segments and reaches n=4096 in 8.41s, giving practical ceilings for exact-label generation.",
      "Maintained correctness gates with 162 collected tests, including plan round-trip tests and oracle cross-checks for solver behavior and reconstruction validity.",
      "Exposed ML-ready surfaces including gold labelers, legality masks, featurization hooks, and candidate metadata for future supervised learning, GNN, and RL experiments."
    ],
    tags: [
      "Optimization",
      "Algorithms",
      "Dynamic Programming",
      "Greedy Algorithms",
      "Computational Geometry",
      "Coverage Planning",
      "Drone Routing",
      "Exact Algorithms",
      "Plan Reconstruction",
      "Dataset Generation",
      "Programmatic Labeling",
      "Featurization",
      "Data QC",
      "Benchmarking",
      "Reproducible Research",
      "Python",
      "NumPy",
      "PyTorch",
      "Pytest",
      "JSONL",
      "GNN",
      "Reinforcement Learning"
    ],
    companyLink: "https://personal.utdallas.edu/~daescu/"
  },
  {
    slug: "abilitie-software-engineering-intern",
    order: 5,
    dateRange: "May 2024 - Aug 2024",
    category: "Industry",
    timelineTone: "past",
    position: "Software Engineering Intern at Abilitie",
    summary:
      "Worked on Abilitie AI Cases, an LLM role-play training product, contributing to product flows, provider plumbing, structured outputs, telemetry, cost optimization, and perceived-latency improvements.",
    description: [
      "Contributed to Abilitie AI Cases, an LLM role-play training product used for scenario-based leadership and communication training.",
      "Built React/TypeScript chat flows, scenario configuration pages, end-state UI fixes, streaming/loading states, and provider request plumbing around Azure/AWS-backed model calls.",
      "Built structured JSON schemas to render LLM responses as product state instead of free-text blobs, making model output easier to validate and display inside the UI.",
      "Optimized role-play prompts, model choice, and output structure across 27 configurations, using scenario testing and human review to improve instruction-following and role-play consistency.",
      "Reduced LLM cost per conversation by ~70% through GPT-4o migration, ~20% fewer prompt tokens, ~8% fewer retries, and structured-output/prompt optimization.",
      "Built a DynamoDB telemetry pipeline for TTFT/TTLT, tokens/sec, token counts, retries, errors, provider/model metadata, and per-request traces.",
      "Used telemetry traces to identify bottlenecks, improve latency by ~10%, and reach ~95% success rate across the monitored role-play flows.",
      "Improved perceived latency with a 3s idle prefetch path and stale-response invalidation, reducing TTFT after send to p95 = 1.5s.",
      "Ran prompt-injection testing and hardening iterations to reduce out-of-format or unsafe model behavior in customer-facing role-play scenarios.",
      "Shipped UI/UX fixes in React + TypeScript + Material UI, including theme-aware rich-text paste handling to prevent dark-mode invisibility in internal/admin workflows."
    ],
    tags: [
      "LLMs",
      "LLM Product Engineering",
      "Software Engineering",
      "React",
      "TypeScript",
      "Azure",
      "AWS",
      "DynamoDB",
      "Telemetry",
      "Observability",
      "Structured Outputs",
      "Prompt Engineering",
      "Model Evaluation",
      "Prompt Injection Testing",
      "Latency Optimization",
      "Cost Optimization",
      "Material UI",
      "Product Engineering"
    ],
    companyLink: "https://www.abilitie.com/case-challenges"
  },
  {
    slug: "st-stephens-dorm-proctor",
    order: 6,
    dateRange: "2021 - 2022",
    category: "Leadership",
    timelineTone: "past",
    position: "Dorm Proctor at St. Stephen's Episcopal School",
    summary:
      "Supported younger boarding students through peer mentorship, safety training, and community-building in a residential school environment.",
    description: [
      "Supported new students as they transitioned into boarding school life, helping them adjust to routines, expectations, and the social environment.",
      "Served as a peer mentor for academic, personal, and social challenges, using training from counselors and dorm staff to respond with discretion and care.",
      "Worked with dorm parents, administrators, and counselors to help maintain a safe, welcoming, and inclusive dorm environment.",
      "Completed safety and emergency training, including fire protocols and campus response procedures.",
      "Balanced proctor responsibilities with academics and extracurriculars, learning how to be dependable in a community-facing leadership role.",
      "Tried to be the person younger students could come to when something felt confusing, stressful, or just awkward about living away from home."
    ],
    tags: [
      "Leadership",
      "Mentorship",
      "Peer Support",
      "Student Life",
      "Counseling",
      "Community Building",
      "Safety Training",
      "Communication"
    ],
    companyLink: "https://www.sstx.org/boarding/boarding-student-support"
  }
];