import type { PortfolioExperience } from "../contracts";

export const portfolioExperiences: PortfolioExperience[] = [
  {
    slug: "utsw-tsai-lab-machine-learning-engineering-intern",
    order: 1,
    dateRange: "Feb 2026 - Present",
    category: "Research",
    timelineTone: "active",
    position:
      "Machine Learning Engineer Intern at UT Southwestern Medical Center, Tsai Lab",
    summary:
      "Fine-tuning DeepLabCut/SuperAnimal for lab-specific 3-chamber mouse-behavior video and building an end-to-end computer vision pipeline for pose extraction, behavioral scoring, QC, and researcher-facing scorecards.",
    description: [
      "Context: Working in the Tsai Lab at UT Southwestern on computer vision tooling for behavioral neuroscience, specifically 3-chamber mouse-behavior videos used to study social interaction and experimental phenotypes.",
      "Problem: Off-the-shelf pose estimation and manual script-based analysis were not enough for reliable lab review; the workflow needed lab-specific model adaptation, consistent post-processing, interpretable QC, and researcher-friendly outputs.",
      "Model architecture: Adapted the DeepLabCut/SuperAnimal pose-estimation stack to domain-specific 3-chamber mouse footage by hand-annotating lab frames and fine-tuning the base model against the visual conditions and behavioral setup used in the lab.",
      "Core implementation: Built the end-to-end ML analysis pipeline from raw video to pose extraction, likelihood-aware filtering, dropped-keypoint interpolation, behavioral metric generation, QC reports, and CSV/XLSX scorecards.",
      "Evaluation and benchmarks: Improved pose-track stability by 56.9% using fine-tuning, likelihood filtering, interpolation, and hardened post-processing across benchmark lab video clips.",
      "Impact and outcome: Turned a fragile, script-heavy analysis workflow into a reproducible computer vision pipeline that produces interpretable pose tracks, behavioral summaries, and lab-review-ready scorecards instead of raw model outputs.",
      "Technical depth: Corrected behavioral scoring logic around discrimination index, ambiguous cup contact, interpolation boundaries, chamber occupancy, occlusion/body-length flags, and low-confidence pose summaries so downstream metrics better match experimental definitions.",
      "What made it hard: The project sits at the intersection of model adaptation, noisy animal video, experimental behavioral definitions, and researcher usability; the system needed to expose uncertainty instead of hiding unreliable trials behind clean-looking outputs.",
    ],
    tags: [
      "Machine Learning",
      "Computer Vision",
      "DeepLabCut",
      "SuperAnimal",
      "Markerless Pose Estimation",
      "Model Fine-Tuning",
      "Domain Adaptation",
      "Behavioral Neuroscience",
      "Behavioral Phenotyping",
      "Mouse Behavior Analysis",
      "Video Analysis",
      "Pose Tracking",
      "Likelihood Filtering",
      "Keypoint Interpolation",
      "QC Tooling",
      "Research Software",
      "Python",
      "OpenCV",
      "pandas",
      "NumPy",
      "HDF5",
      "CSV/XLSX",
    ],
    companyLink: "https://labs.utsouthwestern.edu/tsai-lab",
  },
  {
    slug: "glydr-software-engineer",
    order: 3,
    dateRange: "Jan 2026 - May 2026",
    category: "Product / Platform Engineering",
    timelineTone: "past",
    position: "Software Engineer at Glydr.gg",
    summary:
      "Led engineering for Glydr.gg's Railway-deployed, microservice-based configuration platform serving 1,000+ users, spanning public discovery, Steam authentication, admin tooling, Control Panel imports, CI/CD, and distributed config delivery.",
    description: [
      "Context: Glydr.gg needed a customer-facing configuration hub for discovering, publishing, importing, and managing game-server / controller configuration payloads across public users, admins, and Control Panel workflows.",
      "Problem: The product needed more than static config files; it required authenticated user flows, official/admin publishing, stable versioned imports, repeatable deployments, and safe handoffs into the Control Panel without exposing large or private payloads in URLs.",
      "System architecture: Led engineering for a Railway-deployed, microservice-based platform serving 1,000+ users, with separate frontend, backend API, worker, and database services built around React/Vite, Fastify, PostgreSQL, Drizzle ORM, and GitHub Actions CI/CD.",
      "Core implementation: Built public discovery, Steam authentication, admin tooling, Control Panel imports, config detail pages, official config publishing, private uploads, import success states, and backend-owned session flows.",
      "Data model: Modeled the platform with relational tables for users, Steam identities, sessions, games, categories, configs, immutable config versions, imports, handoff tokens, background jobs, and audit logs.",
      "Security and correctness: Engineered config delivery with checksum-versioned payloads, tokenized imports, throttling, validation guards, HTTP-only cookies, CSRF checks, admin allowlists, stable checksum parsing, and invalid-payload rejection.",
      "Impact and outcome: Turned config sharing/importing into a repeatable product workflow for real users instead of an ad hoc file handoff, while giving the team deployment automation and backend validation for safer iteration.",
      "What made it hard: The platform had to bridge product UX and backend correctness: users needed simple one-click imports, while the system needed stable versioning, safe auth boundaries, replayable imports, and repeatable deploys.",
    ],
    tags: [
      "Software Engineering",
      "Technical Leadership",
      "Product Engineering",
      "Full-Stack Development",
      "Platform Engineering",
      "Microservices",
      "TypeScript",
      "React",
      "Vite",
      "Fastify",
      "PostgreSQL",
      "Drizzle ORM",
      "Railway",
      "GitHub Actions",
      "CI/CD",
      "Steam OpenID",
      "Authentication",
      "CSRF",
      "HTTP-Only Cookies",
      "Rate Limiting",
      "Checksum Validation",
      "Config Versioning",
      "Admin Tooling",
      "API Design",
    ],
    companyLink: "https://glydr.gg/",
  },
  {
    slug: "ut-dallas-undergraduate-researcher-monopolybench",
    order: 2,
    dateRange: "Apr 2025 - Present",
    category: "Research",
    timelineTone: "active",
    position: "Undergraduate Researcher at UT Dallas, CAIR Lab",
    summary:
      "Built MonopolyBench, a deterministic multi-agent LLM benchmark for evaluating tool-calling agents on long-horizon planning, negotiation, deception, bias, memory, and schema-constrained decision-making.",
    description: [
      "Context: Working with the UT Dallas CAIR Lab on agentic AI evaluation, focusing on long-running multi-agent environments where models must plan, negotiate, remember state, and take schema-valid actions over many turns.",
      "Problem: Many LLM-agent evaluations are short, single-agent, or hard to reproduce; MonopolyBench creates a deterministic, replayable environment where agent behavior can be inspected at the level of prompts, tool calls, state transitions, and strategic decisions.",
      "System architecture: Built MonopolyBench as an authoritative rules engine plus multi-agent arena where tool-calling LLM agents play complete Monopoly games through schema-bound actions rather than unconstrained free text.",
      "Core implementation: Implemented deterministic game mechanics including seeded dice/cards, turn order, legal action menus, property ownership, rent, auctions, jail, trades, liquidation, bankruptcy, strict validation, corrective retries, and deterministic fallbacks.",
      "Evaluation design: Designed each decision around game state, recent history, memory, legal action schemas, model responses, parsed actions, tool-call traces, applied events, snapshots, summaries, and replayable artifacts.",
      "Impact and outcome: Built the benchmark infrastructure for a forthcoming agentic AI research paper studying planning, negotiation, deception, and bias in long-horizon, multi-agent game environments.",
      "Technical depth: Added full run telemetry so experiments are debuggable instead of black-box: prompts, raw responses, parsed actions, retries, fallbacks, validation failures, legal menus, state snapshots, and final summaries are all logged for analysis.",
      "What made it hard: The system has to keep LLMs constrained without making the game trivial; every tool-call path needs strict validation, reproducibility, and fallback behavior while preserving meaningful strategic freedom.",
    ],
    tags: [
      "LLM Evaluation",
      "Agentic AI",
      "AI Agents",
      "Multi-Agent Systems",
      "Tool Calling",
      "Function Calling",
      "Agent Benchmarking",
      "Deterministic Simulation",
      "Long-Horizon Planning",
      "Negotiation",
      "Deception",
      "Bias Evaluation",
      "Schema-Bound Actions",
      "JSON Schema",
      "Event Sourcing",
      "Replayable Artifacts",
      "Telemetry",
      "Python",
      "FastAPI",
      "WebSockets",
      "React",
      "TypeScript",
      "Vite",
      "Zod",
      "Pytest",
    ],
    companyLink: "https://cairatutd.github.io/",
  },
  {
    slug: "ut-dallas-undergraduate-researcher-optimization",
    order: 4,
    dateRange: "Apr 2025 - Nov 2025",
    category: "Research",
    timelineTone: "past",
    position: "Independent Researcher (Optimization + ML) at UT Dallas",
    summary:
      "Built paper-faithful optimization solvers and a solver-labeled dataset pipeline for 1D drone coverage planning, with benchmarks and QC gates to support supervised, GNN, and RL experiments on optimal tour planning.",
    description: [
      "Implemented 4 paper-faithful solvers for 1D drone coverage planning (greedy + DP), including exact plan reconstruction so solver outputs can become usable training labels.",
      "Built an end-to-end data pipeline from instance generation → gold labels → featurization hooks → QC, enabling ML training on optimal solutions instead of heuristic approximations.",
      "Measured labeling throughput on a verified run: 370 labeled instances in 2.71s (~136 samples/s), writing ~280KB of JSONL data with automated validation of feasibility and coverage constraints.",
      "Configured defaults for a 67,000-sample labeled dataset across train/test/shifted/extrap/stress splits, supporting generalization and distribution-shift evaluation.",
      "Benchmarked exact solver scaling: dp_full stays under 1s up to n=1024 segments and reaches n=4096 in 8.41s, giving practical ceilings for exact-label generation.",
      "Maintained correctness gates with 162 collected tests, including plan round-trip tests and oracle cross-checks for solver behavior and reconstruction validity.",
      "Exposed ML-ready surfaces including gold labelers, legality masks, featurization hooks, and candidate metadata for future supervised learning, GNN, and RL experiments.",
    ],
    tags: [
      "Optimization",
      "Algorithms",
      "Dynamic Programming",
      "Greedy Algorithms",
      "Computational Geometry",
      "Coverage Planning",
      "Drone Routing",
      "Exact Algorithms",
      "Plan Reconstruction",
      "Dataset Generation",
      "Programmatic Labeling",
      "Featurization",
      "Data QC",
      "Benchmarking",
      "Reproducible Research",
      "Python",
      "NumPy",
      "PyTorch",
      "Pytest",
      "JSONL",
      "GNN",
      "Reinforcement Learning",
    ],
    companyLink: "https://personal.utdallas.edu/~daescu/",
  },
  {
    slug: "abilitie-software-engineering-intern",
    order: 5,
    dateRange: "May 2024 - Aug 2024",
    category: "Industry",
    timelineTone: "past",
    position: "Software Engineering Intern at Abilitie",
    summary:
      "Owned Llama 3.1 fine-tuning, structured-output engineering, cost optimization, telemetry, and latency work for Abilitie AI Cases, reducing LLM cost per conversation 70% across 27 role-play configurations and reaching 1.0s p95 TTFT.",
    description: [
      "Context: Worked on Abilitie AI Cases, an enterprise LLM role-play training product for scenario-based leadership, communication, and decision-making practice.",
      "Problem: The product needed more reliable role-play behavior, lower LLM cost, structured model outputs, better latency visibility, and smoother perceived responsiveness across many scenario configurations.",
      "Model architecture: Owned end-to-end Llama 3.1 fine-tuning on proprietary role-play conversations, scenario data, and structured-output targets to improve domain coaching and JSON/tool-calling behavior.",
      "Core implementation: Built React/TypeScript chat flows, scenario configuration pages, end-state UI fixes, streaming/loading states, and Azure/AWS-backed provider request plumbing around production role-play flows.",
      "Structured output system: Replaced brittle free-text responses with schema-constrained JSON outputs so model responses could be validated, rendered as deterministic product state, and retried when they failed format expectations.",
      "Evaluation and optimization: Reduced LLM cost per conversation 70% across 27 role-play configurations through model migration, prompt compression of roughly 20%, schema-constrained outputs, and retry reduction of roughly 8%.",
      "Telemetry architecture: Built DynamoDB telemetry for TTFT, TTLT, token throughput, token counts, retries, errors, provider/model metadata, and per-request traces, making latency and reliability problems diagnosable instead of anecdotal.",
      "Latency impact: Optimized 3-second idle prefetching and stale-response invalidation to reach 1.0s p95 TTFT in the monitored role-play flow.",
      "Safety and robustness: Ran prompt-injection testing and hardening iterations to reduce out-of-format, unsafe, or scenario-breaking model behavior in customer-facing role-play interactions.",
      "What made it hard: The work required balancing cost, latency, model quality, schema validity, role-play realism, and user experience; optimizing one metric in isolation would have been easy, but the product needed all of them to hold together.",
    ],
    tags: [
      "Software Engineering",
      "LLM Product Engineering",
      "LLMs",
      "Llama 3.1",
      "Fine-Tuning",
      "Structured Outputs",
      "JSON Schema",
      "Tool Calling",
      "Prompt Engineering",
      "Prompt Injection Testing",
      "Model Evaluation",
      "Cost Optimization",
      "Latency Optimization",
      "Telemetry",
      "Observability",
      "DynamoDB",
      "AWS",
      "Azure",
      "React",
      "TypeScript",
      "Material UI",
      "Streaming UX",
      "Product Engineering",
    ],
    companyLink: "https://www.abilitie.com/case-challenges",
  },
  {
    slug: "st-stephens-dorm-proctor",
    order: 6,
    dateRange: "Aug 2021 - May 2022",
    category: "Leadership",
    timelineTone: "past",
    position: "Dorm Proctor at St. Stephen's Episcopal School",
    summary:
      "Supported younger boarding students through peer mentorship, safety training, and community-building in a residential school environment.",
    description: [
      "Supported new students as they transitioned into boarding school life, helping them adjust to routines, expectations, and the social environment.",
      "Served as a peer mentor for academic, personal, and social challenges, using training from counselors and dorm staff to respond with discretion and care.",
      "Worked with dorm parents, administrators, and counselors to help maintain a safe, welcoming, and inclusive dorm environment.",
      "Completed safety and emergency training, including fire protocols and campus response procedures.",
      "Balanced proctor responsibilities with academics and extracurriculars, learning how to be dependable in a community-facing leadership role.",
      "Tried to be the person younger students could come to when something felt confusing, stressful, or just awkward about living away from home.",
    ],
    tags: [
      "Leadership",
      "Mentorship",
      "Peer Support",
      "Student Life",
      "Counseling",
      "Community Building",
      "Safety Training",
      "Communication",
    ],
    companyLink: "https://www.sstx.org/boarding/boarding-student-support",
  },
];
